[camera]
id = 0
w = 800
h = 600
fps = 30

[output]
debug = true
show_lines = true
show_landmarks = false

[hands]

    [hands.model]
        hands_path = "hand_landmarker.task"

    [hands.confidence]
        hand_confidence = 0.6
        tracking_confidence = 0.6
        gesture_confidence = 5 #frames
        inactive_threshold = 2 #frames
    
    [hands.gestures.point]
        enabled = true
        color = [255, 0, 0] #rgb
        radius = 20
        thickness = 5
